version: 1
feature:
  name: ""
  branch: ""
  dir: ""
  created: ""

pipeline:
  mode: auto
  confirm: true
  current_step: specify

  steps:
    - {id: specify,              status: pending}
    - {id: clarify,              status: pending, conditional: true}
    - {id: plan,                 status: pending}
    - {id: planreview,           status: pending}
    - {id: tasks,                status: pending}
    - {id: tasksreview,          status: pending}
    - {id: architecturereview,   status: pending}
    - {id: implement,            status: pending}
    - {id: qualityreview,        status: pending}
    - {id: phasereview,          status: pending}

last_step_summary: ""

context:
  spec_file: ""
  plan_file: ""
  tasks_file: ""
