#!/usr/bin/env bash
# setup-qwen-teammate.sh — Qwen3.5-122B (llama.cpp) を Claude Code ワーカーとして統合するセットアップ
#
# 使い方:
#   bash scripts/setup-qwen-teammate.sh
#
# 前提:
#   - Claude Code (claude) がインストール済み
#   - llama.cpp サーバーが http://10.8.2.1:8080 で稼働中
#   - Node.js がインストール済み
#
# 生成物:
#   /usr/local/bin/qwen              — Qwen3.5 ラッパー（sudo 必要）
#   ~/.claude/qwen-mcp.json          — MCP サーバー設定
#   ~/.config/systemd/user/qwen-thinking-proxy.service — Proxy systemd サービス
#   ~/.bashrc                        — エイリアス追記
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROXY_SCRIPT="${SCRIPT_DIR}/qwen-thinking-proxy.mjs"

LLAMA_HOST="${LLAMA_HOST:-10.8.2.1}"
LLAMA_PORT="${LLAMA_PORT:-8080}"
LLAMA_API_KEY="${LLAMA_API_KEY:-aaaaa}"
PROXY_PORT="${PROXY_PORT:-8081}"

echo "=== Qwen3.5 Teammate Setup ==="
echo ""
echo "  llama.cpp : http://${LLAMA_HOST}:${LLAMA_PORT}"
echo "  Proxy     : http://127.0.0.1:${PROXY_PORT}"
echo ""

# ─── 1. 前提チェック ───
missing=()
for cmd in claude node; do
  command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "ERROR: 以下のコマンドが見つかりません: ${missing[*]}" >&2
  exit 1
fi

if [ ! -f "$PROXY_SCRIPT" ]; then
  echo "ERROR: プロキシスクリプトが見つかりません: $PROXY_SCRIPT" >&2
  exit 1
fi

echo "[OK] 前提チェック完了 (claude, node, proxy script)"

# ─── 2. llama.cpp 接続テスト ───
echo ""
echo "--- llama.cpp 接続テスト ---"
if curl -sf --connect-timeout 5 "http://${LLAMA_HOST}:${LLAMA_PORT}/health" > /dev/null 2>&1; then
  echo "[OK] llama.cpp health check passed"
else
  echo "[WARN] llama.cpp (http://${LLAMA_HOST}:${LLAMA_PORT}/health) に接続できません"
  echo "       サーバーが起動していることを確認してください"
  read -rp "       続行しますか？ [y/N] " cont
  if [[ ! "${cont:-}" =~ ^[Yy] ]]; then
    echo "中断しました"
    exit 1
  fi
fi

# ─── 3. Thinking Strip Proxy — systemd ユーザーサービス ───
echo ""
echo "--- Thinking Strip Proxy セットアップ ---"

SYSTEMD_DIR="$HOME/.config/systemd/user"
mkdir -p "$SYSTEMD_DIR"

cat > "${SYSTEMD_DIR}/qwen-thinking-proxy.service" << EOF
[Unit]
Description=Qwen Thinking Strip Proxy (llama.cpp → Claude Code)
After=network.target

[Service]
Type=simple
ExecStart=$(command -v node) ${PROXY_SCRIPT}
Environment=UPSTREAM_URL=http://${LLAMA_HOST}:${LLAMA_PORT}
Environment=PORT=${PROXY_PORT}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable qwen-thinking-proxy.service
systemctl --user restart qwen-thinking-proxy.service

# Wait for proxy to be ready
sleep 1
if systemctl --user is-active --quiet qwen-thinking-proxy.service; then
  echo "[OK] Proxy サービス起動完了 (port ${PROXY_PORT})"
else
  echo "[WARN] Proxy サービスの起動に失敗しました"
  echo "       journalctl --user -u qwen-thinking-proxy.service で確認してください"
  echo ""
  echo "       手動起動: UPSTREAM_URL=http://${LLAMA_HOST}:${LLAMA_PORT} PORT=${PROXY_PORT} node ${PROXY_SCRIPT}"
fi

# ─── 4. Proxy 動作検証 ───
echo ""
echo "--- Proxy 動作検証 ---"

# Simple test: forward health check through proxy
if curl -sf --connect-timeout 5 "http://127.0.0.1:${PROXY_PORT}/health" > /dev/null 2>&1; then
  echo "[OK] Proxy 経由の health check passed"
else
  echo "[WARN] Proxy 経由の接続に失敗。手動確認が必要です"
fi

# ─── 5. /usr/local/bin/qwen ラッパー生成（sudo） ───
echo ""
echo "--- qwen ラッパー生成 ---"

sudo tee /usr/local/bin/qwen > /dev/null << WRAPPER
#!/usr/bin/env bash
# Claude Code wrapper for Qwen3.5-122B (llama.cpp via thinking-strip proxy)
# Generated by setup-qwen-teammate.sh
set -euo pipefail

# Proxy 経由で llama.cpp に接続（thinking ブロック除去）
export ANTHROPIC_BASE_URL="http://127.0.0.1:${PROXY_PORT}"
export ANTHROPIC_AUTH_TOKEN="${LLAMA_API_KEY}"
export API_TIMEOUT_MS="6000000"

# llama.cpp は単一モデルを提供。エイリアス名は任意
export ANTHROPIC_DEFAULT_OPUS_MODEL="qwen3.5"
export ANTHROPIC_DEFAULT_SONNET_MODEL="qwen3.5"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="qwen3.5"

# ╔══════════════════════════════════════════════════════════════╗
# ║  DO NOT REMOVE: model interception loop                     ║
# ║  Agent Teams passes --model claude-opus-4-6 (full literal   ║
# ║  ID) which bypasses ANTHROPIC_DEFAULT_*_MODEL env vars.     ║
# ║  This loop converts literals to aliases so the env var      ║
# ║  mapping takes effect.                                      ║
# ║  Ref: 3b772dd removed this → broke all team benchmarks.    ║
# ╚══════════════════════════════════════════════════════════════╝
args=()
skip_next=false
for arg in "\$@"; do
  if \$skip_next; then
    skip_next=false
    case "\$arg" in
      *opus*)   args+=("opus") ;;
      *sonnet*) args+=("sonnet") ;;
      *haiku*)  args+=("haiku") ;;
      *)        args+=("\$arg") ;;
    esac
    continue
  fi
  if [[ "\$arg" == "--model" ]]; then
    skip_next=true
    args+=("--model")
    continue
  fi
  args+=("\$arg")
done

# ╔══════════════════════════════════════════════════════════════╗
# ║  DO NOT REMOVE: nested session detection bypass             ║
# ║  Claude Code sets CLAUDECODE=1 in child processes.          ║
# ║  The caller uses CLAUDECODE= (empty) but the variable       ║
# ║  still EXISTS, which triggers the nested session check.     ║
# ║  unset removes the variable entirely so claude launches.    ║
# ║  Ref: 2026-02-23 — CLAUDECODE= broke all bench reviewers.  ║
# ╚══════════════════════════════════════════════════════════════╝
unset CLAUDECODE
exec claude --mcp-config ~/.claude/qwen-mcp.json "\${args[@]}"
WRAPPER
sudo chmod +x /usr/local/bin/qwen
echo "[OK] /usr/local/bin/qwen 生成完了"

# ─── 6. ~/.claude/qwen-mcp.json 作成 ───
echo ""
echo "--- MCP 設定 ---"

mkdir -p "$HOME/.claude"
cat > "$HOME/.claude/qwen-mcp.json" << 'MCP_JSON'
{
  "mcpServers": {
    "deepwiki": {
      "type": "http",
      "url": "https://mcp.deepwiki.com/sse"
    }
  }
}
MCP_JSON
chmod 600 "$HOME/.claude/qwen-mcp.json"
echo "[OK] ~/.claude/qwen-mcp.json 生成完了 (deepwiki)"

# ─── 7. ~/.bashrc にエイリアス追記 ───
echo ""
echo "--- .bashrc 更新 ---"
BASHRC="$HOME/.bashrc"

# Teammate 切替エイリアスを追加
if ! grep -q '# === Qwen3.5 Teammate ===' "$BASHRC" 2>/dev/null; then
  cat >> "$BASHRC" << 'BASHRC_BLOCK'

# === Qwen3.5 Teammate ===
alias use-qwen='export CLAUDE_CODE_TEAMMATE_COMMAND="/usr/local/bin/qwen" && echo "Teammate → Qwen3.5"'
alias use-glm='export CLAUDE_CODE_TEAMMATE_COMMAND="/usr/local/bin/glm" && echo "Teammate → GLM-5"'
BASHRC_BLOCK
  echo "[OK] ~/.bashrc にエイリアス追加 (use-qwen, use-glm)"
else
  echo "[OK] ~/.bashrc のエイリアスは既存"
fi

# ─── 8. 検証 ───
echo ""
echo "=== 検証 ==="
echo "qwen:       $(which qwen 2>/dev/null || echo 'NOT FOUND')"
echo "proxy:      $(systemctl --user is-active qwen-thinking-proxy.service 2>/dev/null || echo 'NOT RUNNING')"
echo "MCP JSON:   $(jq -e . "$HOME/.claude/qwen-mcp.json" >/dev/null 2>&1 && echo 'valid' || echo 'INVALID')"

# Quick integration test
echo ""
echo "--- 統合テスト ---"
if curl -sf --connect-timeout 5 "http://127.0.0.1:${PROXY_PORT}/health" > /dev/null 2>&1; then
  echo "[OK] Proxy → llama.cpp 接続正常"

  # Test thinking strip with a minimal API call
  RESP=$(curl -sf --max-time 120 "http://127.0.0.1:${PROXY_PORT}/v1/messages" \
    -H "x-api-key: ${LLAMA_API_KEY}" \
    -H "content-type: application/json" \
    -H "anthropic-version: 2023-06-01" \
    -d '{
      "model": "qwen3.5",
      "max_tokens": 512,
      "messages": [{"role": "user", "content": "Say hello in one word."}]
    }' 2>/dev/null) || true

  if [ -n "${RESP:-}" ]; then
    HAS_THINKING=$(echo "$RESP" | jq '[.content[]? | select(.type == "thinking")] | length' 2>/dev/null || echo "parse_error")
    if [ "$HAS_THINKING" = "0" ]; then
      echo "[OK] Thinking strip 動作確認: thinking ブロックなし"
      echo "     レスポンス: $(echo "$RESP" | jq -r '[.content[]? | select(.type == "text") | .text] | join("")' 2>/dev/null | head -c 80)"
    elif [ "$HAS_THINKING" = "parse_error" ]; then
      echo "[WARN] レスポンスのパースに失敗"
      echo "       $RESP" | head -c 200
    else
      echo "[FAIL] Thinking ブロックが残っています (${HAS_THINKING} 個)"
      echo "       Proxy のログを確認: journalctl --user -u qwen-thinking-proxy.service"
    fi
  else
    echo "[WARN] API テストでレスポンスなし（llama.cpp の推論に時間がかかっている可能性）"
    echo "       手動テスト: curl http://127.0.0.1:${PROXY_PORT}/v1/messages ..."
  fi
else
  echo "[WARN] Proxy に接続できません。手動で確認してください"
fi

echo ""
echo "=== セットアップ完了 ==="
echo ""
echo "使い方:"
echo "  qwen                  # Qwen3.5 で Claude Code を起動"
echo "  qwen -p 'prompt'      # Qwen3.5 でワンショット実行"
echo "  use-qwen              # Teammate を Qwen3.5 に切替"
echo "  use-glm               # Teammate を GLM-5 に切替"
echo ""
echo "Proxy 管理:"
echo "  systemctl --user status  qwen-thinking-proxy   # ステータス確認"
echo "  systemctl --user restart qwen-thinking-proxy   # 再起動"
echo "  journalctl --user -u qwen-thinking-proxy -f    # ログ監視"
echo ""
echo "注意: 新しいターミナルを開くか、source ~/.bashrc を実行してください。"
